### PR TITLE
updating institutions for plaid

### PR DESCRIPTION
**Pull request by achintgoel**

### CODE REVIEW

**Comment by jollysahil** [comment]
@zp-alfred needs revision
can you update this test: https://github.com/Gusto/plaid-ruby/blob/master/spec/plaid_spec.rb#L67

**Comment by zp-alfred** [comment]
Changes requested by jollysahil.

**Comment by jollysahil** [comment]
@zp-alfred accept

**Comment by zp-alfred** [comment]
Accepted by jollysahil!

**Pull request closed without merging**
