### PR TITLE
fixing bad gateway errors for plaid connect

### PR DESCRIPTION
**Pull request by achintgoel**
https://app.bugsnag.com/gusto-3/zp-rails-fintech-risk/errors/5b3b44cf122dd900194b60b9?filters[event.since][0]=30d&filters[error.status][0]=open

### CODE REVIEW

**Comment by jollysahil** [comment]
@zp-alfred accept

**Comment by zp-alfred** [comment]
Accepted by jollysahil!

**Comment by jollysahil** [comment]
@Karlotcha correct me if i'm wrong, but we will stop using this library, righT?

**Comment by Karlotcha** [comment]
@jollysahil you're right! We will be able to throw all of it away! \o/ 🔥 💯

**Pull request closed without merging**
